<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<Title>Aplicação HotAPP</Title>
		<Description>Aplicação criada com o modelo de aplicação da HotAPP com FluidUI.</Description>

		<Copyright>Marcos Paulo Ferreira Rebello</Copyright>

		<VersionBase>1.0</VersionBase>
		<VersionSuffix>-beta</VersionSuffix>
		<AssemblyVersion>$(VersionBase).$([System.DateTime]::Now.Subtract("2000-01-01").Days).$([System.DateTime]::Now.TimeOfDay.TotalMinutes.ToString("0"))</AssemblyVersion>
		<FileVersion>$(AssemblyVersion)</FileVersion>
		<VersionPrefix>$(AssemblyVersion)</VersionPrefix>
		<Version>$(VersionPrefix)$(VersionSuffix)</Version>
		<UserSecretsId>Senhas</UserSecretsId>

		<GenerateDocumentationFile>True</GenerateDocumentationFile>
		<DocumentationFile>API.xml</DocumentationFile>
	</PropertyGroup>

	<Target Name="EmbedScopedCss" BeforeTargets="BeforeResGen" DependsOnTargets="BundleScopedCssFiles">
		<ItemGroup>
			<EmbeddedResource Include="$(IntermediateOutputPath)scopedcss\bundle\$(AssemblyName).styles.css" LogicalName="$(AssemblyName).wwwroot.styles.css" Type="Non-Resx" WithCulture="false" />
<!--			<EmbeddedResource Include="$(IntermediateOutputPath)win-x64\PubTmp\Out\wwwroot\**" LogicalName="$(AssemblyName).wwwroot.%(RelativeDir).%(FileName)" Type="Non-Resx" WithCulture="false" /> -->
		</ItemGroup>
	</Target>

	<ItemGroup>
		<None Update="appsettings.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<ItemGroup>
		<None Remove="API.xml" />
		<None Remove="appsettings.json" />
		<Compile Remove="wwwroot\_content\**" />
		<None Remove="appsettings.*.json" />
		<None Remove="wwwroot\_content\**" />
	</ItemGroup>

	<ItemGroup>
		<Content Remove="API.xml" />
		<Content Remove="appsettings.json" />
		<Content Remove="appsettings.*.json" />
		<Content Remove="wwwroot\**\*.*" />
		<Content Remove="wwwroot\_content\**" />
		<EmbeddedResource Remove="wwwroot\_content\**" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="API.xml" CopyToPublishDirectory="Never" />
		<EmbeddedResource Include="appsettings.json" />
		<EmbeddedResource Include="wwwroot\**\*.*" />
	</ItemGroup>

	<ItemGroup>
	  <_WebToolingArtifacts Remove="Properties\PublishProfiles\Linux.pubxml" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" Version="1.12.0" />
		<PackageReference Include="HotAPP" Version="1.0.8935.979-beta" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.9.0" />
	</ItemGroup>

</Project>
